-- GENERATED by seed/gen-builders.ts — do not edit by hand.
-- Builders table + Category-A tier; backfills societies.builder_id.

CREATE TABLE builders (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    slug       TEXT NOT NULL UNIQUE,
    tier       TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    CONSTRAINT builders_tier_check CHECK (tier IN ('', 'A', 'B'))
);
CREATE INDEX builders_tier_idx ON builders (tier);

INSERT INTO builders (id, name, slug, tier) VALUES ('afjy3fzk', 'Prestige Group', 'prestige-group', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('6u33xncp', 'Sobha', 'sobha', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('csb7q47x', 'Brigade Group', 'brigade-group', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('5abmd5ph', 'Godrej Properties', 'godrej-properties', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('3vm5riwx', 'Embassy Group', 'embassy-group', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('a5z7elpj', 'Total Environment', 'total-environment', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('io4lm23j', 'Salarpuria Sattva', 'salarpuria-sattva', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('3fnx2fiq', 'Puravankara', 'puravankara', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('w5ezmszz', 'Adarsh Developers', 'adarsh-developers', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('ff6g5nnd', 'Mantri Developers', 'mantri-developers', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('nl4ishis', 'L&T Realty', 'l-t-realty', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('h4ay2sdr', 'Tata Housing', 'tata-housing', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('sooprdia', 'Mahindra Lifespaces', 'mahindra-lifespaces', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('njnswo3m', 'Assetz Property Group', 'assetz-property-group', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('a6vkvkyf', 'Century Real Estate', 'century-real-estate', 'A');
INSERT INTO builders (id, name, slug, tier) VALUES ('yiirmlgb', 'DivyaSree Developers', 'divyasree-developers', '');
INSERT INTO builders (id, name, slug, tier) VALUES ('ynx3v5ml', 'Vaswani Group', 'vaswani-group', '');
INSERT INTO builders (id, name, slug, tier) VALUES ('3yx3w7ns', 'SJR Group', 'sjr-group', '');
INSERT INTO builders (id, name, slug, tier) VALUES ('oiohw4j4', 'Nitesh Estates', 'nitesh-estates', '');
INSERT INTO builders (id, name, slug, tier) VALUES ('x2eh5u55', 'Rohan Builders', 'rohan-builders', '');

ALTER TABLE societies ADD COLUMN builder_id TEXT REFERENCES builders (id);
UPDATE societies SET builder_id = (SELECT id FROM builders WHERE builders.name = societies.builder);
CREATE INDEX societies_builder_idx ON societies (builder_id);
