-- GENERATED by seed/gen-builders-roster.ts from seed/builders.csv — do not edit by hand.
-- Builders roster expansion + enrichment (RENT-vuidxkts). Append-only over 0003.

-- New metadata columns (faithful display + trust signals).
ALTER TABLE builders ADD COLUMN website_url   TEXT    NOT NULL DEFAULT '';
ALTER TABLE builders ADD COLUMN logo_url      TEXT    NOT NULL DEFAULT '';
ALTER TABLE builders ADD COLUMN delivery_risk INTEGER NOT NULL DEFAULT 0;
ALTER TABLE builders ADD COLUMN risk_note     TEXT    NOT NULL DEFAULT '';

-- Old names + sub-brands resolve to the canonical builder (mirrors society_aliases).
CREATE TABLE builder_aliases (
    id         TEXT PRIMARY KEY,
    builder_id TEXT NOT NULL REFERENCES builders (id) ON DELETE CASCADE,
    alias      TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE (builder_id, alias)
);
CREATE INDEX builder_aliases_builder_idx ON builder_aliases (builder_id);

-- Rename: Salarpuria Sattva -> Sattva Group (corporate rebrand).
UPDATE builders  SET name = 'Sattva Group', slug = 'sattva-group' WHERE name = 'Salarpuria Sattva';
UPDATE societies SET builder = 'Sattva Group' WHERE builder = 'Salarpuria Sattva';

-- Roster upsert: insert new builders, refresh tier + metadata on existing
-- ones by unique name. id/slug are left untouched so society FKs stay valid.
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('3mpiq4t6', 'Prestige Group', 'prestige-group', 'A', 'https://www.prestigeconstructions.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('kqhujnq7', 'Sobha', 'sobha', 'A', 'https://www.sobha.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('5hdcv7zl', 'Brigade Group', 'brigade-group', 'A', 'https://www.brigadegroup.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('ec76mrce', 'Puravankara', 'puravankara', 'A', 'https://www.puravankara.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('hl2b2mjr', 'Sattva Group', 'sattva-group', 'A', 'https://www.sattvagroup.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('yldbiwrh', 'Godrej Properties', 'godrej-properties', 'A', 'https://www.godrejproperties.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('obevf2l5', 'Embassy Group', 'embassy-group', 'A', 'https://www.embassygroup.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('okk36zul', 'Adarsh Developers', 'adarsh-developers', 'A', 'https://www.adarshdevelopers.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('jyr7rbvk', 'Total Environment', 'total-environment', 'A', 'https://www.totalenvironment.in', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('odrwxy6n', 'Tata Housing', 'tata-housing', 'A', 'https://www.tatahousing.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('thnxauy3', 'Mahindra Lifespaces', 'mahindra-lifespaces', 'A', 'https://www.mahindralifespaces.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('26ed4llv', 'L&T Realty', 'l-t-realty', 'A', 'https://www.lntrealty.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('li2nylgx', 'Assetz Property Group', 'assetz-property-group', 'A', 'https://www.assetzproperty.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('ok3gg5d6', 'Century Real Estate', 'century-real-estate', 'A', 'https://www.centuryrealestate.in', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('tmd363bg', 'Sumadhura Group', 'sumadhura-group', 'A', 'https://www.sumadhuragroup.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('fw2cibhp', 'Sterling Developers', 'sterling-developers', 'A', 'https://www.sterlingdevelopers.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('a4tu3hvq', 'Bhartiya City', 'bhartiya-city', 'A', 'https://www.bhartiyacity.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('zc2kg5o3', 'Lodha', 'lodha', 'A', 'https://www.lodhagroup.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('bo2r2i7j', 'Birla Estates', 'birla-estates', 'A', 'https://www.birlaestates.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('dpobsysc', 'Mantri Developers', 'mantri-developers', 'B', '', '', 1, 'Insolvency proceedings (NCLT Bengaluru 2023; later settled) plus multiple Karnataka RERA delay/refund orders. Kept searchable for resident rent data; not featured.')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('w6ulyf2d', 'Shriram Properties', 'shriram-properties', 'B', 'https://www.shriramproperties.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('jglr7jok', 'Provident Housing', 'provident-housing', 'B', 'https://www.providenthousing.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('5dfwcyrh', 'Gopalan Enterprises', 'gopalan-enterprises', 'B', 'https://www.gopalanenterprises.com', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('c352i27n', 'Casagrand', 'casagrand', 'B', 'https://www.casagrand.co.in', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('b5jemel5', 'Concorde Group', 'concorde-group', 'B', 'https://www.concorde.in', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('co63vos7', 'DivyaSree Developers', 'divyasree-developers', 'B', '', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('avtir4th', 'Vaswani Group', 'vaswani-group', 'B', '', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('asjnwulp', 'SJR Group', 'sjr-group', 'B', '', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('ejfui2jr', 'Nitesh Estates', 'nitesh-estates', 'B', '', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;
INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)
VALUES ('wpolhv7j', 'Rohan Builders', 'rohan-builders', 'B', '', '', 0, '')
ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,
  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;

-- Aliases: resolve old names / sub-brands to the canonical builder row.
INSERT OR IGNORE INTO builder_aliases (id, builder_id, alias)
SELECT 'vnz6mlmm', id, 'Salarpuria Sattva' FROM builders WHERE name = 'Sattva Group';
INSERT OR IGNORE INTO builder_aliases (id, builder_id, alias)
SELECT 'gfuzsh5s', id, 'Sobha Limited' FROM builders WHERE name = 'Sobha';
INSERT OR IGNORE INTO builder_aliases (id, builder_id, alias)
SELECT '52uhlxdt', id, 'Assetz' FROM builders WHERE name = 'Assetz Property Group';
INSERT OR IGNORE INTO builder_aliases (id, builder_id, alias)
SELECT 'qufiow2h', id, 'Bhartiya Urban' FROM builders WHERE name = 'Bhartiya City';
INSERT OR IGNORE INTO builder_aliases (id, builder_id, alias)
SELECT 'dc6ia7si', id, 'Nikoo Homes' FROM builders WHERE name = 'Bhartiya City';
INSERT OR IGNORE INTO builder_aliases (id, builder_id, alias)
SELECT '5sf2zm3s', id, 'Macrotech Developers' FROM builders WHERE name = 'Lodha';
