// Generates migrations/0014_rent_observations.sql from seed/rent-observations.csv.
//
//   node seed/gen-rent-observations.ts
//
// This wires the research-harness rent dataset (asking-price-derived, RENT-dqfzfbeq)
// into the catalog. It:
//   - creates a rent_observations table: the canonical per-(society,BHK) store of
//     sourced asking-rent snapshots (also the future sink for the Google-CSE feeder
//     and, conceptually, aggregated resident submissions),
//   - inserts every observation from the CSV,
//   - updates each society's headline medians/ranges from its observations and sets
//     provenance='estimated' (the schema's "from listings / asking prices" tier),
//   - applies data-integrity corrections the research surfaced: NULLs fabricated
//     2BHK numbers on villa/3BHK-only societies (any society with no 2BHK row in the
//     CSV), and fixes mis-seeded localities.
//
// Asking-derived only — NOT resident-paid. societies has no maintenance/deposit
// columns, so those stay in rent_observations until the detail page is D1-backed
// (RENT-tbhkjjfy); the browse cards + sparse detail pages pick up the new medians.
//
// NOTE the headline UPDATE only touches societies present in the CSV. Two seed rows
// are deliberately EXCLUDED pending a human decision (see EXISTENCE_FLAGS) because
// the research could not confirm they exist as described.
//
// Committed output is the source of truth (random ids freeze on generate). Re-run
// only when the CSV changes.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const CSV = join(HERE, "rent-observations.csv");
const OUT = join(HERE, "..", "migrations", "0014_rent_observations.sql");

// Mis-seeded localities the research corrected (society real, locality wrong).
const LOCATION_FIXES: Record<string, string> = {
  "brigade-caladium": "Hebbal",
  "total-environment-after-the-rain": "Yelahanka",
  "brigade-northridge": "Yelahanka",
};

// Seed societies the research could not confirm exist as described — left
// untouched here; need a keep/fix/remove decision (see RENT-dqfzfbeq).
const EXISTENCE_FLAGS = [
  "salarpuria-sattva-magnus", // no "Sattva Magnus" in Bengaluru (only Hyderabad)
  "prestige-sunrise-park", // only exists in Electronics City Ph1, seed says Bellandur
];

const BASE32 = "abcdefghijklmnopqrstuvwxyz234567";
function newShortID(): string {
  const b = new Uint8Array(5);
  crypto.getRandomValues(b);
  let bits = 0, value = 0, out = "";
  for (let i = 0; i < b.length; i++) {
    value = (value << 8) | b[i];
    bits += 8;
    while (bits >= 5) { out += BASE32[(value >>> (bits - 5)) & 31]; bits -= 5; }
  }
  if (bits > 0) out += BASE32[(value << (5 - bits)) & 31];
  return out;
}

const sql = (s: string) => `'${s.replace(/'/g, "''")}'`;
const intOrNull = (s: string): string => {
  const n = parseInt((s ?? "").replace(/[^0-9]/g, ""), 10);
  return Number.isFinite(n) && (s ?? "").trim() !== "" ? String(n) : "NULL";
};

// Quote-aware CSV parser (note fields are quoted, may contain commas).
function parseCsv(text: string): Record<string, string>[] {
  const rows: string[][] = [];
  let field = "", row: string[] = [], inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else inQuotes = false; }
      else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      if (field !== "" || row.length > 0) { row.push(field); rows.push(row); field = ""; row = []; }
    } else field += c;
  }
  if (field !== "" || row.length > 0) { row.push(field); rows.push(row); }
  const header = rows[0];
  return rows.slice(1).map((r) => Object.fromEntries(header.map((h, i) => [h, (r[i] ?? "").trim()])));
}

const records = parseCsv(readFileSync(CSV, "utf8")).filter((r) => r.society_slug);

// Group by society to build one UPDATE each.
const bySociety = new Map<string, Record<string, Record<string, string>>>();
for (const r of records) {
  if (!bySociety.has(r.society_slug)) bySociety.set(r.society_slug, {});
  bySociety.get(r.society_slug)![r.bhk] = r;
}

const out: string[] = [];
out.push("-- GENERATED by seed/gen-rent-observations.ts from seed/rent-observations.csv — do not edit by hand.");
out.push("-- Grounded asking-rent data + corrections (RENT-dqfzfbeq). Append-only.");
out.push("");
out.push(`CREATE TABLE rent_observations (
    id                  TEXT PRIMARY KEY,
    society_slug        TEXT NOT NULL REFERENCES societies (slug) ON UPDATE CASCADE ON DELETE CASCADE,
    bhk                 TEXT NOT NULL,
    asking_low          INTEGER,
    asking_median       INTEGER,
    asking_high         INTEGER,
    maintenance_monthly INTEGER,
    deposit_months      INTEGER,
    listings_basis      INTEGER,
    confidence          TEXT NOT NULL DEFAULT '',
    observed_on         TEXT NOT NULL DEFAULT '',
    sources             TEXT NOT NULL DEFAULT '',
    note                TEXT NOT NULL DEFAULT '',
    provenance          TEXT NOT NULL DEFAULT 'estimated',
    created_at          TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE (society_slug, bhk, observed_on)
);`);
out.push("CREATE INDEX rent_observations_society_idx ON rent_observations (society_slug);");
out.push("");

out.push("-- Observations (asking-derived snapshots, with sources).");
for (const r of records) {
  out.push(
    `INSERT INTO rent_observations (id, society_slug, bhk, asking_low, asking_median, asking_high, maintenance_monthly, deposit_months, listings_basis, confidence, observed_on, sources, note)\n` +
      `VALUES (${sql(newShortID())}, ${sql(r.society_slug)}, ${sql(r.bhk)}, ${intOrNull(r.asking_low)}, ${intOrNull(r.asking_median)}, ${intOrNull(r.asking_high)}, ${intOrNull(r.maintenance_monthly)}, ${intOrNull(r.deposit_months)}, ${intOrNull(r.listings_basis)}, ${sql(r.confidence)}, ${sql(r.observed_on)}, ${sql(r.sources)}, ${sql(r.note)});`,
  );
}
out.push("");

out.push("-- Headline medians/ranges from observations; provenance -> 'estimated'");
out.push("-- (asking-derived). Societies with no 2BHK observation get their fabricated");
out.push("-- 2BHK numbers NULLed (villa/3BHK-only communities).");
for (const [slug, bhks] of bySociety) {
  const two = bhks["2BHK"];
  const three = bhks["3BHK"];
  const set = [
    `median_rent_2bhk = ${two ? intOrNull(two.asking_median) : "NULL"}`,
    `range_2bhk_low = ${two ? intOrNull(two.asking_low) : "NULL"}`,
    `range_2bhk_high = ${two ? intOrNull(two.asking_high) : "NULL"}`,
    `median_rent_3bhk = ${three ? intOrNull(three.asking_median) : "NULL"}`,
    `range_3bhk_low = ${three ? intOrNull(three.asking_low) : "NULL"}`,
    `range_3bhk_high = ${three ? intOrNull(three.asking_high) : "NULL"}`,
    `provenance = 'estimated'`,
    `last_updated = '2026-05-31T00:00:00Z'`,
  ];
  out.push(`UPDATE societies SET ${set.join(", ")} WHERE slug = ${sql(slug)};`);
}
out.push("");

out.push("-- Locality corrections (society real, seed locality wrong).");
for (const [slug, loc] of Object.entries(LOCATION_FIXES)) {
  out.push(`UPDATE societies SET locality = ${sql(loc)} WHERE slug = ${sql(slug)};`);
}
out.push("");

out.push("-- EXISTENCE FLAGS (left untouched, need keep/fix/remove decision):");
for (const slug of EXISTENCE_FLAGS) out.push(`--   ${slug}`);
out.push("");

writeFileSync(OUT, out.join("\n"));
const noTwo = [...bySociety].filter(([, b]) => !b["2BHK"]).length;
console.log(`Wrote ${OUT}: ${records.length} observations, ${bySociety.size} societies updated (${noTwo} with 2BHK NULLed), ${Object.keys(LOCATION_FIXES).length} locality fixes.`);
