// Generates migrations/0003_builders.sql: a builders table (id, name, slug,
// tier), seeded from a curated Category-A list + every builder already present
// in societies.csv, then backfills societies.builder_id by name match.
//
//   node seed/gen-builders.ts
//
// Category-A = premium/grade-A builders whose societies surface on the homepage
// featured strip. Non-A builders stay fully searchable, just not featured. This
// is a DB flag (editable in admin later), NOT a hardcoded allowlist.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const CSV = join(HERE, "societies.csv");
const OUT = join(HERE, "..", "migrations", "0003_builders.sql");

const BASE32 = "abcdefghijklmnopqrstuvwxyz234567";
function newShortID(): string {
  const b = new Uint8Array(5);
  crypto.getRandomValues(b);
  let bits = 0, value = 0, out = "";
  for (let i = 0; i < b.length; i++) {
    value = (value << 8) | b[i];
    bits += 8;
    while (bits >= 5) { out += BASE32[(value >>> (bits - 5)) & 31]; bits -= 5; }
  }
  if (bits > 0) out += BASE32[(value << (5 - bits)) & 31];
  return out;
}

const slugify = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

// Curated Category-A builders (brand grade-A in Bengaluru). Pre-added even if
// they have no seeded society yet, so future societies select rather than type.
const CATEGORY_A = [
  "Prestige Group",
  "Sobha",
  "Brigade Group",
  "Godrej Properties",
  "Embassy Group",
  "Total Environment",
  "Salarpuria Sattva",
  "Puravankara",
  "Adarsh Developers",
  "Mantri Developers",
  "L&T Realty",
  "Tata Housing",
  "Mahindra Lifespaces",
  "Assetz Property Group",
  "Century Real Estate",
];

// Distinct builder names from the society seed (so every existing society
// backfills to a builder row).
function csvBuilders(): string[] {
  const text = readFileSync(CSV, "utf8");
  const rows = text.split(/\r?\n/).filter(Boolean);
  const header = rows[0].split(",");
  const bIdx = header.indexOf("builder");
  const names = new Set<string>();
  for (let i = 1; i < rows.length; i++) {
    // builder is column 3 and never contains a comma in this seed; split is safe.
    const cols = rows[i].split(",");
    const name = (cols[bIdx] ?? "").trim();
    if (name) names.add(name);
  }
  return [...names];
}

const sql = (s: string) => `'${s.replace(/'/g, "''")}'`;

// Union: curated A list + CSV builders. Tier 'A' for curated; '' otherwise.
const byName = new Map<string, { tier: string }>();
for (const n of CATEGORY_A) byName.set(n, { tier: "A" });
for (const n of csvBuilders()) if (!byName.has(n)) byName.set(n, { tier: "" });

const out: string[] = [];
out.push("-- GENERATED by seed/gen-builders.ts — do not edit by hand.");
out.push("-- Builders table + Category-A tier; backfills societies.builder_id.");
out.push("");
out.push(`CREATE TABLE builders (
    id         TEXT PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    slug       TEXT NOT NULL UNIQUE,
    tier       TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    CONSTRAINT builders_tier_check CHECK (tier IN ('', 'A', 'B'))
);`);
out.push("CREATE INDEX builders_tier_idx ON builders (tier);");
out.push("");

let a = 0;
for (const [name, { tier }] of byName) {
  if (tier === "A") a++;
  out.push(
    `INSERT INTO builders (id, name, slug, tier) VALUES (${sql(newShortID())}, ${sql(name)}, ${sql(slugify(name))}, ${sql(tier)});`,
  );
}
out.push("");
// Nullable FK column (SQLite ALTER ADD COLUMN allows a REFERENCES with NULL default).
out.push("ALTER TABLE societies ADD COLUMN builder_id TEXT REFERENCES builders (id);");
out.push("UPDATE societies SET builder_id = (SELECT id FROM builders WHERE builders.name = societies.builder);");
out.push("CREATE INDEX societies_builder_idx ON societies (builder_id);");
out.push("");

writeFileSync(OUT, out.join("\n"));
console.log(`Wrote ${OUT}: ${byName.size} builders (${a} Category-A).`);
