// Generates migrations/0002_seed_societies.sql from seed/societies.csv.
// Run once (committed output is the source of truth); re-run only when the
// CSV changes. Build-time only — NOT shipped to the Worker.
//
//   node seed/gen-seed.ts
//
// Emits upserts so the seed is safe even if re-applied: societies upsert on
// slug (refreshing metadata in place, mirroring the Go UpsertSocietyFromSeed),
// aliases insert-or-ignore on (society_id, alias).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const CSV = join(HERE, "societies.csv");
const OUT = join(HERE, "..", "migrations", "0002_seed_societies.sql");

const BASE32 = "abcdefghijklmnopqrstuvwxyz234567"; // RFC 4648, lowercased
function newShortID(): string {
  const b = new Uint8Array(5);
  crypto.getRandomValues(b);
  let bits = 0, value = 0, out = "";
  for (let i = 0; i < b.length; i++) {
    value = (value << 8) | b[i];
    bits += 8;
    while (bits >= 5) {
      out += BASE32[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) out += BASE32[(value << (5 - bits)) & 31];
  return out;
}

// Minimal RFC-4180-ish CSV parser: handles quoted fields, embedded commas,
// doubled-quote escapes, and CRLF. Sufficient for this hand-authored seed.
function parseCSV(text: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ",") {
      row.push(field); field = "";
    } else if (c === "\n") {
      row.push(field); field = "";
      rows.push(row); row = [];
    } else if (c === "\r") {
      // swallow; \n handles the row break
    } else field += c;
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows.filter((r) => r.length > 1 || (r.length === 1 && r[0] !== ""));
}

const sqlStr = (s: string) => `'${s.replace(/'/g, "''")}'`;
const sqlInt = (s: string) => (s.trim() === "" ? "NULL" : String(parseInt(s, 10)));
const sqlNullStr = (s: string) => (s.trim() === "" ? "NULL" : sqlStr(s));

const rows = parseCSV(readFileSync(CSV, "utf8"));
const header = rows[0];
const idx = (name: string) => header.indexOf(name);
const col = {
  slug: idx("slug"), name: idx("name"), locality: idx("locality"), builder: idx("builder"),
  yFrom: idx("year_built_from"), yTo: idx("year_built_to"), units: idx("total_units"),
  desc: idx("description"), aliases: idx("aliases"),
  m2: idx("median_rent_2bhk"), r2lo: idx("range_2bhk_low"), r2hi: idx("range_2bhk_high"),
  m3: idx("median_rent_3bhk"), r3lo: idx("range_3bhk_low"), r3hi: idx("range_3bhk_high"),
  reports: idx("report_count"), updated: idx("last_updated"),
  conf: idx("confidence_label"), featured: idx("featured_bhk"),
};

const out: string[] = [];
out.push("-- GENERATED by seed/gen-seed.ts from seed/societies.csv — do not edit by hand.");
out.push("-- 36-society Bengaluru catalog + aliases. Upserts so re-apply is safe.");
out.push("");

let societyCount = 0;
let aliasCount = 0;

for (let i = 1; i < rows.length; i++) {
  const r = rows[i];
  if (!r[col.slug]) continue;
  const id = newShortID();
  societyCount++;
  out.push(
    "INSERT INTO societies (id, slug, name, locality, builder, year_built_from, year_built_to, " +
      "total_units, description, median_rent_2bhk, range_2bhk_low, range_2bhk_high, median_rent_3bhk, " +
      "range_3bhk_low, range_3bhk_high, report_count, last_updated, confidence_label, featured_bhk, " +
      "status, source) VALUES (",
  );
  out.push(
    "  " +
      [
        sqlStr(id), sqlStr(r[col.slug]), sqlStr(r[col.name]), sqlStr(r[col.locality] ?? ""),
        sqlStr(r[col.builder] ?? ""), sqlInt(r[col.yFrom] ?? ""), sqlInt(r[col.yTo] ?? ""),
        sqlInt(r[col.units] ?? ""), sqlStr(r[col.desc] ?? ""), sqlInt(r[col.m2] ?? ""),
        sqlInt(r[col.r2lo] ?? ""), sqlInt(r[col.r2hi] ?? ""), sqlInt(r[col.m3] ?? ""),
        sqlInt(r[col.r3lo] ?? ""), sqlInt(r[col.r3hi] ?? ""), sqlInt(r[col.reports] ?? ""),
        sqlNullStr(r[col.updated] ?? ""), sqlStr(r[col.conf] ?? ""), sqlStr(r[col.featured] ?? ""),
        "'published'", "'seed'",
      ].join(", "),
  );
  out.push(
    ") ON CONFLICT(slug) DO UPDATE SET name=excluded.name, locality=excluded.locality, " +
      "builder=excluded.builder, year_built_from=excluded.year_built_from, year_built_to=excluded.year_built_to, " +
      "total_units=excluded.total_units, description=excluded.description, median_rent_2bhk=excluded.median_rent_2bhk, " +
      "range_2bhk_low=excluded.range_2bhk_low, range_2bhk_high=excluded.range_2bhk_high, " +
      "median_rent_3bhk=excluded.median_rent_3bhk, range_3bhk_low=excluded.range_3bhk_low, " +
      "range_3bhk_high=excluded.range_3bhk_high, report_count=excluded.report_count, " +
      "last_updated=excluded.last_updated, confidence_label=excluded.confidence_label, " +
      "featured_bhk=excluded.featured_bhk;",
  );

  const aliasField = (r[col.aliases] ?? "").trim();
  if (aliasField) {
    for (const alias of aliasField.split(";").map((a) => a.trim()).filter(Boolean)) {
      aliasCount++;
      out.push(
        `INSERT INTO society_aliases (id, society_id, alias) VALUES (${sqlStr(newShortID())}, ${sqlStr(id)}, ${sqlStr(alias)}) ON CONFLICT(society_id, alias) DO NOTHING;`,
      );
    }
  }
  out.push("");
}

writeFileSync(OUT, out.join("\n"));
console.log(`Wrote ${OUT}: ${societyCount} societies, ${aliasCount} aliases.`);
