// Generates migrations/0011_builders_roster.sql from seed/builders.csv.
//
//   node seed/gen-builders-roster.ts
//
// This is the CURRENT source of truth for the builders roster. migrations/0003
// (generated by gen-builders.ts) created the original 20-builder table and is
// historical/applied — never regenerate it. This generator emits an append-only
// 0011 that:
//   - adds website_url / logo_url / delivery_risk / risk_note columns,
//   - creates a builder_aliases table (old names + sub-brands resolve here),
//   - renames Salarpuria Sattva -> Sattva Group (old name kept as an alias),
//   - upserts the full roster by unique name (INSERT new, refresh tier+metadata
//     on existing rows WITHOUT touching their id/slug, so society FKs stay put),
//   - records aliases, and keeps societies.builder text in sync on rename.
//
// Re-run only when builders.csv changes; the committed .sql is what ships.
// Idempotent on re-apply: ON CONFLICT upserts + INSERT OR IGNORE aliases.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const CSV = join(HERE, "builders.csv");
const OUT = join(HERE, "..", "migrations", "0011_builders_roster.sql");

const BASE32 = "abcdefghijklmnopqrstuvwxyz234567"; // RFC 4648, lowercased
function newShortID(): string {
  const b = new Uint8Array(5);
  crypto.getRandomValues(b);
  let bits = 0, value = 0, out = "";
  for (let i = 0; i < b.length; i++) {
    value = (value << 8) | b[i];
    bits += 8;
    while (bits >= 5) { out += BASE32[(value >>> (bits - 5)) & 31]; bits -= 5; }
  }
  if (bits > 0) out += BASE32[(value << (5 - bits)) & 31];
  return out;
}

// Matches the slugify in gen-builders.ts / src/data/builders.ts so slugs are
// stable across generators.
const slugify = (s: string) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

const sql = (s: string) => `'${s.replace(/'/g, "''")}'`;

// Minimal RFC-4180-ish parser: handles double-quoted fields with embedded
// commas and "" escapes. builders.csv has one quoted field (risk_note).
function parseCsv(text: string): Record<string, string>[] {
  const rows: string[][] = [];
  let field = "", row: string[] = [], inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQuotes = false;
      } else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      if (field !== "" || row.length > 0) { row.push(field); rows.push(row); field = ""; row = []; }
    } else field += c;
  }
  if (field !== "" || row.length > 0) { row.push(field); rows.push(row); }
  const header = rows[0];
  return rows.slice(1).map((r) => Object.fromEntries(header.map((h, i) => [h, (r[i] ?? "").trim()])));
}

const records = parseCsv(readFileSync(CSV, "utf8")).filter((r) => r.name);

const out: string[] = [];
out.push("-- GENERATED by seed/gen-builders-roster.ts from seed/builders.csv — do not edit by hand.");
out.push("-- Builders roster expansion + enrichment (RENT-vuidxkts). Append-only over 0003.");
out.push("");
out.push("-- New metadata columns (faithful display + trust signals).");
out.push("ALTER TABLE builders ADD COLUMN website_url   TEXT    NOT NULL DEFAULT '';");
out.push("ALTER TABLE builders ADD COLUMN logo_url      TEXT    NOT NULL DEFAULT '';");
out.push("ALTER TABLE builders ADD COLUMN delivery_risk INTEGER NOT NULL DEFAULT 0;");
out.push("ALTER TABLE builders ADD COLUMN risk_note     TEXT    NOT NULL DEFAULT '';");
out.push("");
out.push(`-- Old names + sub-brands resolve to the canonical builder (mirrors society_aliases).
CREATE TABLE builder_aliases (
    id         TEXT PRIMARY KEY,
    builder_id TEXT NOT NULL REFERENCES builders (id) ON DELETE CASCADE,
    alias      TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE (builder_id, alias)
);`);
out.push("CREATE INDEX builder_aliases_builder_idx ON builder_aliases (builder_id);");
out.push("");

// Renames must run before the upserts so the upsert matches on the new name.
const aliasInserts: Array<{ builderName: string; alias: string }> = [];
for (const r of records) {
  if (r.rename_from) {
    out.push(`-- Rename: ${r.rename_from} -> ${r.name} (corporate rebrand).`);
    out.push(`UPDATE builders  SET name = ${sql(r.name)}, slug = ${sql(slugify(r.name))} WHERE name = ${sql(r.rename_from)};`);
    out.push(`UPDATE societies SET builder = ${sql(r.name)} WHERE builder = ${sql(r.rename_from)};`);
    out.push("");
    aliasInserts.push({ builderName: r.name, alias: r.rename_from });
  }
}

out.push("-- Roster upsert: insert new builders, refresh tier + metadata on existing");
out.push("-- ones by unique name. id/slug are left untouched so society FKs stay valid.");
let aCount = 0, bCount = 0;
for (const r of records) {
  if (r.tier === "A") aCount++; else if (r.tier === "B") bCount++;
  const risk = r.delivery_risk === "1" ? 1 : 0;
  out.push(
    `INSERT INTO builders (id, name, slug, tier, website_url, logo_url, delivery_risk, risk_note)\n` +
      `VALUES (${sql(newShortID())}, ${sql(r.name)}, ${sql(slugify(r.name))}, ${sql(r.tier)}, ${sql(r.website_url)}, ${sql(r.logo_url)}, ${risk}, ${sql(r.risk_note)})\n` +
      `ON CONFLICT(name) DO UPDATE SET tier = excluded.tier, website_url = excluded.website_url,\n` +
      `  logo_url = excluded.logo_url, delivery_risk = excluded.delivery_risk, risk_note = excluded.risk_note;`,
  );
  for (const a of (r.aliases ? r.aliases.split(";") : [])) {
    if (a.trim()) aliasInserts.push({ builderName: r.name, alias: a.trim() });
  }
}
out.push("");

if (aliasInserts.length) {
  out.push("-- Aliases: resolve old names / sub-brands to the canonical builder row.");
  for (const a of aliasInserts) {
    out.push(
      `INSERT OR IGNORE INTO builder_aliases (id, builder_id, alias)\n` +
        `SELECT ${sql(newShortID())}, id, ${sql(a.alias)} FROM builders WHERE name = ${sql(a.builderName)};`,
    );
  }
  out.push("");
}

writeFileSync(OUT, out.join("\n"));
console.log(`Wrote ${OUT}: ${records.length} builders (${aCount} A, ${bCount} B), ${aliasInserts.length} aliases.`);
