// Generates migrations/0018_expand_catalog.sql from the 2026-06 expansion batch:
//   seed/expansion-2026-06-societies.csv        (society metadata)
//   seed/expansion-2026-06-rent-observations.csv (asking-rent snapshots + sources)
//
//   node seed/gen-expansion-2026-06.ts
//
// This is the manual research-harness expansion (see DATA_AGENT.md §1/§4): adds
// occupied, ready-to-move Bengaluru societies for previously-zero-coverage tier-A
// builders (Tata Housing, Birla Estates, L&T Realty, Mahindra Lifespaces, Assetz,
// Sumadhura, Bhartiya City, Century, Sterling). Rents are asking-derived, so every
// new society is provenance='estimated' ("Estimated from current listings").
//
// It emits a NEW, append-only migration (0018) — it does NOT touch the frozen
// 0002 (gen-seed) or 0014 (gen-rent-observations) inputs, so re-running this never
// disturbs already-applied migrations. The migration itself is re-apply-safe:
// INSERT OR IGNORE on the unique society slug and the unique
// (society_slug, bhk, observed_on) on rent_observations, and a NULL-only builder_id
// backfill (same pattern as 0004).
//
// Headline median_rent_2bhk/3bhk + ranges are derived HERE from the 2BHK/3BHK
// observations (single source of truth for rents); 1BHK/4BHK observations are still
// stored in rent_observations for the detail page but don't drive the headline
// (societies has only 2BHK/3BHK columns). report_count = sum of listings_basis the
// estimate is based on (capped at 45 so a deep-inventory society doesn't distort the
// homepage "estimated points" counter); confidence_label keys the card variant.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const SOC_CSV = join(HERE, "expansion-2026-06-societies.csv");
const OBS_CSV = join(HERE, "expansion-2026-06-rent-observations.csv");
const OUT = join(HERE, "..", "migrations", "0018_expand_catalog.sql");

const LAST_UPDATED = "2026-06-13T00:00:00Z";
const REPORT_COUNT_CAP = 45;

const BASE32 = "abcdefghijklmnopqrstuvwxyz234567";
function newShortID(): string {
  const b = new Uint8Array(5);
  crypto.getRandomValues(b);
  let bits = 0, value = 0, out = "";
  for (let i = 0; i < b.length; i++) {
    value = (value << 8) | b[i];
    bits += 8;
    while (bits >= 5) { out += BASE32[(value >>> (bits - 5)) & 31]; bits -= 5; }
  }
  if (bits > 0) out += BASE32[(value << (5 - bits)) & 31];
  return out;
}

const sql = (s: string) => `'${s.replace(/'/g, "''")}'`;
const intOrNull = (s: string): string => {
  const v = (s ?? "").replace(/[^0-9]/g, "");
  return v !== "" ? String(parseInt(v, 10)) : "NULL";
};
const intOr = (s: string, dflt: number): number => {
  const v = (s ?? "").replace(/[^0-9]/g, "");
  return v !== "" ? parseInt(v, 10) : dflt;
};

// Quote-aware CSV parser (description / note fields are quoted, may contain commas).
function parseCsv(text: string): Record<string, string>[] {
  const rows: string[][] = [];
  let field = "", row: string[] = [], inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else inQuotes = false; }
      else field += c;
    } else if (c === '"') inQuotes = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      if (field !== "" || row.length > 0) { row.push(field); rows.push(row); field = ""; row = []; }
    } else field += c;
  }
  if (field !== "" || row.length > 0) { row.push(field); rows.push(row); }
  const header = rows[0];
  return rows.slice(1).map((r) => Object.fromEntries(header.map((h, i) => [h, (r[i] ?? "").trim()])));
}

const societies = parseCsv(readFileSync(SOC_CSV, "utf8")).filter((r) => r.slug);
const observations = parseCsv(readFileSync(OBS_CSV, "utf8")).filter((r) => r.society_slug);

// Group observations by society for headline derivation.
const obsBySociety = new Map<string, Record<string, Record<string, string>>>();
for (const r of observations) {
  if (!obsBySociety.has(r.society_slug)) obsBySociety.set(r.society_slug, {});
  obsBySociety.get(r.society_slug)![r.bhk] = r;
}

// Every society in the metadata CSV must have at least one observation; flag drift.
for (const s of societies) {
  if (!obsBySociety.has(s.slug)) throw new Error(`society ${s.slug} has no rent observations`);
}
const knownSlugs = new Set(societies.map((s) => s.slug));
for (const slug of obsBySociety.keys()) {
  if (!knownSlugs.has(slug)) throw new Error(`observation references unknown society ${slug}`);
}

const out: string[] = [];
out.push("-- GENERATED by seed/gen-expansion-2026-06.ts — do not edit by hand.");
out.push("-- 2026-06 catalog expansion: occupied societies for previously-zero-coverage");
out.push("-- tier-A builders. Asking-derived rents (provenance='estimated'). Append-only,");
out.push("-- re-apply-safe (INSERT OR IGNORE on unique slug / (society,bhk,observed_on)).");
out.push("");
out.push("-- 1. New society rows (published, source 'seed', provenance 'estimated').");
out.push("--    Headline 2BHK/3BHK medians + ranges derived from the observations below.");

for (const s of societies) {
  const obs = obsBySociety.get(s.slug)!;
  const two = obs["2BHK"];
  const three = obs["3BHK"];
  const totalBasis = Object.values(obs).reduce((acc, o) => acc + intOr(o.listings_basis, 0), 0);
  const reportCount = Math.min(REPORT_COUNT_CAP, Math.max(2, totalBasis));
  const confidenceLabel = totalBasis >= 10 ? "partially verified" : "limited data";
  out.push(
    `INSERT OR IGNORE INTO societies (id, slug, name, locality, builder, city, year_built_from, year_built_to, total_units, description, median_rent_2bhk, range_2bhk_low, range_2bhk_high, median_rent_3bhk, range_3bhk_low, range_3bhk_high, report_count, last_updated, confidence_label, featured_bhk, status, source, provenance)\n` +
      `VALUES (${sql(newShortID())}, ${sql(s.slug)}, ${sql(s.name)}, ${sql(s.locality)}, ${sql(s.builder)}, ${sql(s.city)}, ${intOrNull(s.year_built_from)}, ${intOrNull(s.year_built_to)}, ${intOrNull(s.total_units)}, ${sql(s.description)}, ` +
      `${two ? intOrNull(two.asking_median) : "NULL"}, ${two ? intOrNull(two.asking_low) : "NULL"}, ${two ? intOrNull(two.asking_high) : "NULL"}, ` +
      `${three ? intOrNull(three.asking_median) : "NULL"}, ${three ? intOrNull(three.asking_low) : "NULL"}, ${three ? intOrNull(three.asking_high) : "NULL"}, ` +
      `${reportCount}, ${sql(LAST_UPDATED)}, ${sql(confidenceLabel)}, ${sql(s.featured_bhk)}, 'published', 'seed', 'estimated');`,
  );
}
out.push("");
out.push("-- 2. Link builder_id by exact builder-name match (same pattern as 0004).");
out.push("--    Only NULL builder_ids are touched, so this is idempotent and never");
out.push("--    re-points an existing society. All nine builders already exist in the roster.");
out.push("UPDATE societies");
out.push("SET builder_id = (SELECT id FROM builders WHERE builders.name = societies.builder)");
out.push("WHERE builder_id IS NULL AND TRIM(builder) <> '';");
out.push("");
out.push("-- 3. Rent observations (asking-derived snapshots, with sources).");
for (const r of observations) {
  out.push(
    `INSERT OR IGNORE INTO rent_observations (id, society_slug, bhk, asking_low, asking_median, asking_high, maintenance_monthly, deposit_months, listings_basis, confidence, observed_on, sources, note)\n` +
      `VALUES (${sql(newShortID())}, ${sql(r.society_slug)}, ${sql(r.bhk)}, ${intOrNull(r.asking_low)}, ${intOrNull(r.asking_median)}, ${intOrNull(r.asking_high)}, ${intOrNull(r.maintenance_monthly)}, ${intOrNull(r.deposit_months)}, ${intOrNull(r.listings_basis)}, ${sql(r.confidence)}, ${sql(r.observed_on)}, ${sql(r.sources)}, ${sql(r.note)});`,
  );
}
out.push("");

writeFileSync(OUT, out.join("\n"));
console.log(`Wrote ${OUT}: ${societies.length} societies, ${observations.length} observations.`);
